### ISSUE TITLE
The normal way of loading the package gives type errors

### ISSUE THREAD

**Issue by JesseWynants** [prezly/javascript-sdk#22] opened 2021-01-25 08:31 UTC
`const Prezly = require('@prezly/sdk');`

Gave a TypeError when using the library.

`const Prezly = require('@prezly/sdk').default;`

Did fix it.

**Comment by e1himself** [comment] 2021-01-27 12:08
Hey @JesseWynants 

Thanks for posting this issue!

However, I believe this is not a bug. This is a typical quirk of using an ES module from CommonJS code.
This is even mentioned in the readme: https://github.com/prezly/javascript-sdk/blob/master/README.md#using-the-code

That being said, I'm closing this as not-a-bug.

Have a great day :)

**Closed** 2021-01-27 12:08 UTC
Labels: bug, dependencies, wontfix
